# Numpy Cheat Sheet
CREATE FROM LIST | OPERANDS

In [10]:
import numpy as np

___

## 1. Creating 2D arrays from list

In [16]:
# Lists
weight = [65.4, 59.2, 36.6, 88.4, 68.7]
height = [60.4, 57.2, 26.6, 78.4, 58.7]

array = np.array([weight, height])
array

array([[65.4, 59.2, 36.6, 88.4, 68.7],
       [60.4, 57.2, 26.6, 78.4, 58.7]])

___

## 2. Operands

In [29]:
array2 = np.array([[2, 4, 6],  
                   [2, 4, 6]])
array3 = np.array([[2, 4, 6],  
                   [2, 4, 6]])

- #### Addition

In [60]:
array2 + array3

array([[ 4,  8, 12],
       [ 4,  8, 12]])

- #### Subtraction

In [59]:
array2 - array3

array([[0, 0, 0],
       [0, 0, 0]])

- #### Multiply

In [58]:
array2 * array3

array([[ 4, 16, 36],
       [ 4, 16, 36]])

In [38]:
multiply_2 = array2 * 2
multiply_2

array([[ 4,  8, 12],
       [ 4,  8, 12]])

- #### Divide

In [57]:
array2 / array3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
array2 / 2

array([[1., 2., 3.],
       [1., 2., 3.]])

- #### Raise to power

In [55]:
array2 ** array3

array([[    4,   256, 46656],
       [    4,   256, 46656]])

In [54]:
array3 ** 2

array([[ 4, 16, 36],
       [ 4, 16, 36]])