# Numpy Cheat Sheet
1-D ARRAY INDEXING | 2D ARRAY INDEXING

In [53]:
import numpy as np
import pandas as pd

____

## 1. 1-D Array Indexing


In [54]:
bmi = np.array([21.852, 20.975, 21.75, 24.747, 21.441])
print(bmi)

[21.852 20.975 21.75  24.747 21.441]


In [55]:
bmi[0]

21.852

In [18]:
bmi[1]

20.975

In [19]:
bmi[-1]

21.441

In [20]:
bmi[0:1]

array([21.852])

In [21]:
bmi[0:2]

array([21.852, 20.975])

In [23]:
bmi[:]

array([21.852, 20.975, 21.75 , 24.747, 21.441])

In [24]:
bmi[0:]

array([21.852, 20.975, 21.75 , 24.747, 21.441])

In [25]:
bmi[1:]

array([20.975, 21.75 , 24.747, 21.441])

___

## 2. 2-D Array Indexing

In [138]:
# Lists
weight = [1, 2, 3, 4, 5, 6]
height = [11, 12, 13, 14, 15, 16]
weight_2 = [21, 22, 23, 24, 25, 26]
height_2 = [31, 32, 33, 34, 35, 36]

array2d = np.array([weight, height, weight_2, height_2])

In [126]:
array2d[:]

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36]])

In [127]:
array2d[0:1]

array([[1, 2, 3, 4, 5, 6]])

In [128]:
array2d[1:]

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36]])

In [129]:
array2d[-1:]

array([[31, 32, 33, 34, 35, 36]])

In [136]:
array2d[0,0]

1

In [118]:
array2d[0,3]

4

In [118]:
array2d[0,3]

4

In [137]:
array2d[0, :]

array([1, 2, 3, 4, 5, 6])

In [133]:
array2d[0:,3]

array([ 4, 14, 24, 34])

In [134]:
array2d[1:3, :]

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

____

## 3. Boolean

In [36]:
bmi = np.array([21.852, 20.975, 21.75, 24.747, 21.441])
print(bmi)

[21.852 20.975 21.75  24.747 21.441]


In [34]:
bmi > 21

array([ True, False,  True,  True,  True])

In [35]:
bmi[bmi > 21]

array([21.852, 21.75 , 24.747, 21.441])

___

In [91]:
players = pd.read_csv('Datasets/fifa.csv')

# Select column fields height and position
# Positions are either 'GK', 'M', 'A', OR 'D'
height = players[' height']
position = players[' position']

#comvert to arrays
np_height = np.array(height)
np_position = np.array(position)

np_height
#np_position

array([191, 184, 185, ..., 183, 179, 179])

In [81]:
# Select the height of players who's positions are GK

GK_heights = np_height[np_position == ' GK']
#GK_heights

In [83]:
np_height[100: 105]

array([178, 192, 172, 170, 190])

In [85]:
np_height > 185

array([ True, False, False, ..., False, False, False])

In [86]:
np_height[np_height > 185]

array([191, 187, 186, ..., 196, 196, 189])