# Numpy Cheat Sheet
1-D ARRAY INDEXING | 2D ARRAY INDEXING

In [1]:
import numpy as np
import pandas as pd

____

## 1. 1-D Array Indexing


In [2]:
bmi = np.array([21.852, 20.975, 21.75, 24.747, 21.441])
print(bmi)

[21.852 20.975 21.75  24.747 21.441]


In [3]:
bmi[0]

21.852

In [4]:
bmi[1]

20.975

In [5]:
bmi[-1]

21.441

In [6]:
bmi[0:1]

array([21.852])

In [7]:
bmi[0:2]

array([21.852, 20.975])

In [8]:
bmi[:]

array([21.852, 20.975, 21.75 , 24.747, 21.441])

In [9]:
bmi[0:]

array([21.852, 20.975, 21.75 , 24.747, 21.441])

In [10]:
bmi[1:]

array([20.975, 21.75 , 24.747, 21.441])

___

## 2. 2-D Array Indexing

In [11]:
# Lists
weight = [1, 2, 3, 4, 5, 6]
height = [11, 12, 13, 14, 15, 16]
weight_2 = [21, 22, 23, 24, 25, 26]
height_2 = [31, 32, 33, 34, 35, 36]

array2d = np.array([weight, height, weight_2, height_2])

In [12]:
array2d[:]

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36]])

In [13]:
array2d[0:1]

array([[1, 2, 3, 4, 5, 6]])

In [14]:
array2d[1:]

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36]])

In [15]:
array2d[-1:]

array([[31, 32, 33, 34, 35, 36]])

In [16]:
array2d[0,0]

1

In [17]:
array2d[0,3]

4

In [18]:
array2d[0,3]

4

In [19]:
array2d[0, :]

array([1, 2, 3, 4, 5, 6])

In [20]:
array2d[0:,3]

array([ 4, 14, 24, 34])

In [21]:
array2d[1:3, :]

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

____

## 3. Boolean

In [22]:
bmi = np.array([21.852, 20.975, 21.75, 24.747, 21.441])
print(bmi)

[21.852 20.975 21.75  24.747 21.441]


In [23]:
bmi > 21

array([ True, False,  True,  True,  True])

In [24]:
bmi[bmi > 21]

array([21.852, 21.75 , 24.747, 21.441])

___

In [25]:
players = pd.read_csv('Datasets/fifa.csv')

# Select column fields height and position
# Positions are either 'GK', 'M', 'A', OR 'D'
height = players[' height']
position = players[' position']

#comvert to arrays
np_height = np.array(height)
np_position = np.array(position)

np_height
#np_position

array([191, 184, 185, ..., 183, 179, 179])

In [26]:
# Select the height of players who's positions are GK

GK_heights = np_height[np_position == ' GK']
#GK_heights

In [27]:
np_height[100: 105]

array([178, 192, 172, 170, 190])

In [28]:
np_height > 185

array([ True, False, False, ..., False, False, False])

In [29]:
np_height[np_height > 185]

array([191, 187, 186, ..., 196, 196, 189])

____

## 4. NP logical

In [30]:
brics = pd.read_csv('Datasets/brics.csv', index_col = 0)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

- #### and

In [31]:
area_8_10 = np.logical_and(brics['area'] > 8, brics['area'] < 10)
brics[area_8_10]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

- #### or

In [32]:
area_8_or_10 = np.logical_or(brics['area'] > 8, brics['area'] < 10)
brics[area_8_or_10]

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98