# For Loop Cheat Sheet

In [1]:
import numpy as np
import pandas as pd

___

## 1. Strings as Range

In [2]:
message = 'Man'

In [3]:
for i in message:
    print(i)

M
a
n


___

## 2. Range as Range

In [4]:
for i in range(3):
    print(i)

0
1
2


- range 0 to 10, step of 2

In [5]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


___

## 3. Nested List as Range

In [6]:
house = [['hallway', 11.25],['kitchen', 18.0], ['kiving room', 20.0], ['bedroom', 10.75], ['bathroom', 9.50]]

In [7]:
for i in house:
    print(i)

['hallway', 11.25]
['kitchen', 18.0]
['kiving room', 20.0]
['bedroom', 10.75]
['bathroom', 9.5]


- for the first iteration i is ['hallway', 11.25]. therefor i[0] is "hallway"

In [8]:
for i in house:
    print('the ' + i[0] + ' is ' + str(i[1]) + ' sqm')
    

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the kiving room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


___

## 4. Dictionary as Range

In [9]:
world = {'iran':30.55, 'albania':2.77, 'algeria': 39.21}

In [10]:
for key, value in world.items():
    print(key + ':' +  str(value))

iran:30.55
albania:2.77
algeria:39.21


In [11]:
for country, population in world.items():
    print(country + ':' +  str(population))

iran:30.55
albania:2.77
algeria:39.21


___

## 5. Numpy Array as Range

In [12]:
height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
weight = np.array([1.25, 1.23, 1.24, 1.29, 1.22])

In [13]:
for item in height:
    print(item)

1.73
1.68
1.71
1.89
1.79


#### - 2D Array

In [17]:
np_2d = np.array([height, weight])
np_2d

array([[1.73, 1.68, 1.71, 1.89, 1.79],
       [1.25, 1.23, 1.24, 1.29, 1.22]])

In [18]:
for item in np_2d:
    print(item , '\n')

[1.73 1.68 1.71 1.89 1.79] 

[1.25 1.23 1.24 1.29 1.22] 



In [19]:
for item in np.nditer(np_2d):
    print(item)

1.73
1.68
1.71
1.89
1.79
1.25
1.23
1.24
1.29
1.22


___

## 6. DataFrame as Range

In [20]:
brics = pd.read_csv('Datasets/brics.csv', index_col = 0)
# brics.index = [label[0:2] for label in brics['country']]
display(brics)

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [22]:
for val in brics:
    print(val)

country
capital
area
population


In [23]:
for label, row in brics.iterrows():
    print(label + ":" + row['capital'])

BR:Brasilia
RU:Moscow
IN:New Delhi
CH:Beijing
SA:Pretoria


In [31]:
for label, row in brics.iterrows():
    print(label)
    print(row)
    print('\n')

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object


RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object


IN
country           India
capital       New Delhi
area              3.286
population         1252
Name: IN, dtype: object


CH
country         China
capital       Beijing
area            9.597
population       1357
Name: CH, dtype: object


SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object




___

## 7. Enumrate

In [25]:
avengers = ['hawkeye', 'hulk', 'thor', 'quicksilver']
e = enumerate(avengers)
print(e)
print(list(e))

[(0, 'hawkeye'), (1, 'hulk'), (2, 'thor'), (3, 'quicksilver')]


In [26]:
for index, value in enumerate(avengers):
    print(index, value)

0 hawkeye
1 hulk
2 thor
3 quicksilver


In [27]:
for index, value in enumerate(avengers, start=10):
    print(index, value)

10 hawkeye
11 hulk
12 thor
13 quicksilver


In [28]:
fam = [1, 2, 3, 4, 5, 6, 7, 8, 9]

for i, j in enumerate(fam):
    print('index' , i , ':', j)

index 0 : 1
index 1 : 2
index 2 : 3
index 3 : 4
index 4 : 5
index 5 : 6
index 6 : 7
index 7 : 8
index 8 : 9


___

## 8. Zip

In [29]:
avengers = ['hawkeye', 'hulk', 'thor', 'quicksilver']
names = ['barton', 'dr', 'odinson', 'maximoff']

z = zip(avengers, names)
print(z)
print(list(z))

[('hawkeye', 'barton'), ('hulk', 'dr'), ('thor', 'odinson'), ('quicksilver', 'maximoff')]


In [30]:
for z1, z2 in zip(avengers, names):
    print(z1, ':', z2)

hawkeye : barton
hulk : dr
thor : odinson
quicksilver : maximoff
