# Boolean Cheat Sheet

___

## 1. String Logic

In [6]:
'carl' < 'chris'

True

___

## 2. Operators

In [19]:
my_kitchen = 18.0
your_kitchen = 14.0
x = 8 
y = 9

In [15]:
print(my_kitchen > 10 and my_kitchen < 18)
print(10 < my_kitchen < 18)

False
False


In [17]:
print(my_kitchen > 17 or my_kitchen < 14)

True


In [21]:
print(not(not(x < 3) and not(y > 14 or y > 10)))

False


___

## 3. Numpy

In [25]:
import numpy as np
bmi = np.array([21.852, 20.975, 21.75, 24.747, 21.441])

In [27]:
bmi > 21

array([ True, False,  True,  True,  True])

In [28]:
bmi < 22

array([ True,  True,  True, False,  True])

In [29]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [30]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.852, 21.75 , 21.441])

___

## 4. Pandas

In [38]:
import pandas as pd
brics = pd.read_csv('Datasets/brics.csv', index_col = 0)
display(brics)

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [40]:
brics['area'] > 9

BR    False
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [41]:
brics[brics['area'] > 9]

country  capital    area  population
RU  Russia   Moscow  17.100       143.5
CH   China  Beijing   9.597      1357.0

In [43]:
np.logical_and(brics['area'] > 8, brics['area'] < 10)

BR     True
RU    False
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [44]:
brics[np.logical_and(brics['area'] > 8, brics['area'] < 10)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0

In [47]:
brics[np.logical_and(brics['area'] > 8, brics['population'] > 200)]

country   capital   area  population
BR  Brazil  Brasilia  8.516       200.4
CH   China   Beijing  9.597      1357.0